#!/bin/bash

amount=${2:0}
case "$1" in
	increase)
		light -Ap $amount
		;;
	decrease)
		light -Up $amount
		;;
	max)
		light -Sp 100
		;;
	min)
		light -Sp 1%
		;;
	*)
		echo "Usage: $0 {increase|decrease|max|min|none} {amount}"
		exit 2
esac
exit 0