#!/bin/bash

amount=${2:0}
device=alsa_output.pci-0000_00_1b.0.analog-stereo
case "$1" in
    notify)
	vollevel=$(pactl list sinks | grep '^[[:space:]]Volume:' | \
		       head -n $(( 1 + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

	notify-send "Volume Level:" $vollevel --urgency=low --expire-time=100
	;;
    increase)
	pactl set-sink-volume $device +$amount%
	;;
    decrease)
	pactl set-sink-volume $device -$amount%
	;;
    toggle)
	pactl set-sink-mute $device toggle
	;;
    *)
	echo "Usage: $0 {increase|decrease|mute|nomute|toggle} {amount}"
	exit 2
esac
exit 0
