(load "~/.emacs.d/init/basic_editor_settings.el")
(load "~/.emacs.d/init/foundational.el")
(load "~/.emacs.d/init/general.el")
(load "~/.emacs.d/init/misc_packages.el")
(load "~/.emacs.d/init/aesthetics.el")
(load "~/.emacs.d/init/evil.el")
(load "~/.emacs.d/init/org.el")
(load "~/.emacs.d/init/programming_language_integration_packages.el")
