(load "~/.emacs.d/init/basic_editor_settings.el")
(load "~/.emacs.d/init/evil_and_related_packages.el")
(load "~/.emacs.d/init/programming_language_integration_packages.el")
(load "~/.emacs.d/init/misc_packages.el")
(load "~/.emacs.d/init/aesthetics.el")
